services:
  - type: web
    name: yolov5-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      git clone https://github.com/ultralytics/yolov5.git
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT

envVars:
  - key: YOLO_CONFIG_DIR
    value: /tmp
